server:
  port: 8116

spring:
  application:
    name: jpa-performance
  datasource:
    url: jdbc:postgresql://localhost:8118/dvdrental
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true



